ALTER TABLE productos
  ADD COLUMN tiempo_horas NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN precio_hora NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN porcentaje_ganancia NUMERIC(5,2) NOT NULL DEFAULT 0;
